# Template only — must be moved to ios/fastlane/Fastfile after
# `flutter create .` generates the ios/ directory. See Android.Fastfile in
# this same folder for the parallel setup steps.
#
# iOS distribution additionally requires an Apple Developer Program
# enrollment ($99/year), a signing certificate, and a provisioning profile
# — real account/credential setup that cannot be generated by any script,
# fastlane's `match` lane helps manage those once you have them, not before.

default_platform(:ios)

platform :ios do
  desc "Build a release IPA"
  lane :build do
    sh("flutter build ipa --release --dart-define=API_BASE_URL=#{ENV['API_BASE_URL']}")
  end

  desc "Upload to TestFlight"
  lane :beta do
    build
    upload_to_testflight(
      ipa: "../build/ios/ipa/quickcart_app.ipa",
      api_key_path: ENV["APPSTORE_API_KEY_PATH"] # path to your App Store Connect API key
    )
  end
end
